version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11.3
    
    steps:
      - checkout

      - run:
          name: install dependencies
          command: pip install -r requirements.txt

      # - run:
      #     name: Start Docker daemon
      #     command: |
      #       sudo service docker start
      #       sleep 5  # Wait for Docker daemon to start
      
      - docker/build:
          image: python
