version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.3
    
    steps:
      - checkout

      - run:
          name: install dependencies
          command: pip install -r requirements.txt

      # - run:
      #     name: Start Docker daemon
      #     command: |
      #       sudo service docker start
      #       sleep 5  # Wait for Docker daemon to start
      
      - run:
          name: build docker image
          command: docker build -t python-ci:${CIRCLE_SHA1} .
