version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  slack: circleci/slack@4.4.4

jobs:
  build-image:
    # docker:
    #   - image: docker
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: gopikrishna99899/python-test
          tag: latest
      - docker/push:
          image: gopikrishna99899/python-test
          tag: latest
workflows:
  build-docker-image-only:
    jobs:
      - build-image:
          context: docker-hub
      
          

