version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    
    steps:
      - checkout

      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      
      - run:
          name: build docker image
          command: docker build -t python-ci:${CIRCLE_SHA1} .
